"""CybOrg environment client.

Friendly wrapper around the raw OpenEnv WebSocket protocol. Importantly, it
exposes ``step_red(...)`` / ``step_blue(...)`` helpers for trainers that want
to be explicit about which side they're scoring even when the environment is
in dual mode.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

from openenv.core import EnvClient
from openenv.core.client_types import StepResult
from openenv.core.env_server.types import State

from .models import CybOrgAction, CybOrgObservation, CybOrgState


class CybOrg(EnvClient[CybOrgAction, CybOrgObservation, CybOrgState]):
    """HTTP/WebSocket client for the CybOrg environment.

    Example:
        >>> with CybOrg(base_url="http://localhost:8000") as env:
        ...     obs = env.reset(seed=7, task="red_easy", difficulty="easy")
        ...     while not obs.observation.done:
        ...         obs = env.step_red("scan", target="dmz-00")
    """

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------
    def step_red(self, tool: str, **args: Any) -> StepResult[CybOrgObservation]:
        return self.step(CybOrgAction(tool=tool, args=args, role="red"))

    def step_blue(self, tool: str, **args: Any) -> StepResult[CybOrgObservation]:
        return self.step(CybOrgAction(tool=tool, args=args, role="blue"))

    # ------------------------------------------------------------------
    # Required EnvClient hooks
    # ------------------------------------------------------------------
    def _step_payload(self, action: CybOrgAction) -> Dict:
        # Dump pydantic model so dict types like args round-trip correctly.
        return action.model_dump(exclude_none=True)

    def _parse_result(self, payload: Dict) -> StepResult[CybOrgObservation]:
        obs_data = payload.get("observation", {})
        observation = CybOrgObservation.model_validate(obs_data)
        # The HTTP server reports done/reward at the top level; sync them onto
        # the observation so callers can rely on either path.
        observation.done = bool(payload.get("done", observation.done))
        if payload.get("reward") is not None:
            observation.reward = payload["reward"]
        return StepResult(
            observation=observation,
            reward=payload.get("reward", observation.reward),
            done=observation.done,
        )

    def _parse_state(self, payload: Dict) -> CybOrgState:
        return CybOrgState.model_validate(payload)


# Backwards-compatible alias for code generated by ``openenv init``.
CybOrgEnv = CybOrg
